---
- name: Deploy Webserver on VM1 and VM2
  hosts: webservers
  become: yes
  tasks:
    # Install Apache web server
    - name: Install Apache web server
      apt:
        name: apache2
        state: present
        update_cache: yes

    # Ensure Python is installed
    - name: Ensure Python is installed
      apt:
        name: python3
        state: present

    # Configure Apache to listen on port 8080
    - name: Change Apache to listen on port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80'
        line: 'Listen 8080'

    - name: Update default virtual host to use port 8080
      lineinfile:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: '^<VirtualHost \*:80>'
        line: '<VirtualHost *:8080>'

    # Restart Apache to apply changes
    - name: Restart Apache service
      service:
        name: apache2
        state: restarted
      become: yes

    # Create index.html with custom message
    - name: Create index.html on VM1
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from SJSU-1"
      when: "'vm1' in inventory_hostname"

    - name: Create index.html on VM2
      copy:
        dest: /var/www/html/index.html
        content: "Hello World from SJSU-2"
      when: "'vm2' in inventory_hostname"

    # Enable Apache service on boot
    - name: Ensure Apache is enabled on boot
      systemd:
        name: apache2
        enabled: yes

